### ISSUE TITLE
Request for APK

### ISSUE THREAD

**Issue by hackintoshlover** [grammesm/SandBot-Android#2]
Hi, Thanks for the amazing project.
Need your help with two things.
1) How do i control led strip from the sandUI or cncUI?
2) Could you provide the apk file for the app?
Thanks.

**Comment by BramWerbrouck** [comment]
Hi,

you can download the latest APK file [here](https://alwaystinkering.com/files/sandbot-debug-v4.apk)

Maybe, if you are a good programmer you could help me with the app. I have some issues, see [here](https://github.com/grammesm/SandBot-Android/issues/1)

**Comment by hackintoshlover** [comment]
> Hi,
> 
> you can download the latest APK file [here](https://alwaystinkering.com/files/sandbot-debug-v4.apk)
> 
> Maybe, if you are a good programmer you could help me with the app. I have some issues, see [here](https://github.com/grammesm/SandBot-Android/issues/1)

Hi, Thanks for the quick response.
I am afraid I cannot help you with Android app development.

One question I have though, no matter whatever I do whichever files I play, the status on app homepage is always idle.
Is this a bug or did I do something wrong?
Thanks

**Comment by BramWerbrouck** [comment]
I don't have any issues with playing a file.

however, you could try a previous version:

[Version 1](https://alwaystinkering.com/files/sandbot-debug-v1.apk)
[Version 2](https://alwaystinkering.com/files/sandbot-debug-v2.apk)
[Version 3](https://alwaystinkering.com/files/sandbot-debug-v3.apk)

**Comment by hackintoshlover** [comment]
Will check with the same.
Thanks.

**Comment by Usamat494** [comment]
hi friend, hope you are doing great. friends i am facing a problem that when i gave ip in the app and come back to home page and if my esp32 is connected to the network then my app continuously keep closing. if i turn off the esp32 then app will open perfect but shows disconnected, if i again turn on esp32 then after few sec the app will close automatically, it look like if esp32 and app are connected then app closes. i have not connected any circuit or sd card module to the esp32. esp32 is not yet connected or wired to anything. is that the issue?. i have tried all version of this app like v1, v2, v3, v4...

**Comment by Usamat494** [comment]
> Hi,
> 
> you can download the latest APK file [here](https://alwaystinkering.com/files/sandbot-debug-v4.apk)
> 
> Maybe, if you are a good programmer you could help me with the app. I have some issues, see [here](https://github.com/grammesm/SandBot-Android/issues/1)

hi friend, hope you are doing great. friends i am facing a problem that when i gave ip in the app and come back to home page and if my esp32 is connected to the network then my app continuously keep closing. if i turn off the esp32 then app will open perfect but shows disconnected, if i again turn on esp32 then after few sec the app will close automatically, it look like if esp32 and app are connected then app closes. i have not connected any circuit or sd card module to the esp32. esp32 is not yet connected or wired to anything. is that the issue?. i have tried all version of this app like v1, v2, v3, v4...
